# Generated by Django 4.2.5 on 2023-09-11 17:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctor",
            old_name="doctor_number",
            new_name="phone",
        ),
    ]
