# Generated by Django 4.2.5 on 2023-09-11 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0002_rename_doctor_number_doctor_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="slot",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="appointment.category",
            ),
        ),
    ]
