# Generated by Django 4.2.5 on 2023-09-12 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0005_alter_doctor_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="slot",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="appointment.patient",
            ),
        ),
    ]
