# Generated by Django 4.2.5 on 2023-09-25 14:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0007_attendance_present"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="entry_time",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="exit_time",
        ),
    ]
