# Generated by Django 4.2.5 on 2023-09-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0008_remove_attendance_entry_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctor_id", models.CharField(max_length=9)),
                ("patient_name", models.CharField(max_length=100)),
                ("attended", models.CharField(max_length=50)),
                ("category_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="PatientCategoryPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_name", models.CharField(max_length=100)),
                ("category_id", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="slot",
            name="status",
            field=models.CharField(default="Available", max_length=20),
        ),
    ]
