# Generated by Django 4.2.5 on 2023-09-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0009_patientallocation_patientcategorypreference_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="present",
            field=models.BooleanField(default=True),
        ),
    ]
