# Generated by Django 4.2.5 on 2023-09-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0010_doctor_present"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="waitlist_count",
            field=models.IntegerField(default=0),
        ),
    ]
